import numpy as np

H = 27 # The smoothing radius, particles that are distance greater than this away from a given particle have no influence on said particle
HSqrd = H**2

particleMass = 1.0 #Assumed constant for a uniform fluid

# Defining important fluid constant
restingDensity = 75.0
fluidStiffness = 0.175
dynamicViscosity = 0.025

"""
Within Smoothed paticle Hydrodynamics, there is something always used called a 'smoothing kernel,' which essentially, for a given particle, looks at the immediate neighbors of that
particles an obtains values for those particles contributions to 3 main things, density, pressure, and viscosity. I'll admit, the math for this is pretty difficult and I don't fully
understand it, but the smoothing kernal looks something like: ρᵢ = Σ m · W(|rᵢ - rⱼ|, h)
What this is basically saying is that function "w" takes in the distance between the two particles and a user-defined smoothing radius 'h' and returns the three values previously mentioned
of density, pressure, and viscosity all weighted by the particles separation distance.

Taken from the internet, these are the mathematical functions that need to be returned:
W(r, h)   = (1 - (r/h)²)²          for density
∇W(r, h)  = -4r/h² · (1 - (r/h)²)  for pressure
∇²W(r, h) = (1 - r/h)              for viscosity 
"""

def W_density(r, h): # this function determines how much a given particle a distance "r" away contributes to a particles local density
    if r >= h:
        return 0
    else:
        return (1 - (r/h)**2)**2 # this math comes from a research paper, don't really know what is means
    
def W_pressure_gradient(r_vector, r_magn, h):
    if r_magn >= h or r_magn == 0:
        return np.zeros(2)
    scalar = -4 * r_magn / h**2 * (1 - (r_magn/h)**2)
    return scalar * (r_vector / r_magn) # returns a unit vector scalaed by the 'scalar' which determines how 'strong' the pressure forces acts along this unit vector

def W_viscosity_laplacian(r, h): # The laplacian is a m
    if r >= h:
        return 0.0
    return (1 - r/h)

def densityToColor(density, restDensity):
    ratio = density / restDensity  # restDensity should be ~4-5 to match actual values
    if ratio < 0.4:
        return (135, 206, 235)   # light blue — sparse
    elif ratio < 0.7:
        return (30, 144, 255)    # dodger blue
    elif ratio < 1.0:
        return (0, 0, 205)       # medium blue — near rest
    elif ratio < 1.5:
        return (0, 0, 139)       # dark blue — compressed
    else:
        return (255, 255, 255)   # white — very compressed

# These next two functions were mainly generated by AI, although I know what they do high level, I wasn't able to obtain these math relationships myself
def computeDensityPressure(particles, tree, app):
    """Pass 1: compute density and pressure for every particle"""
    positions = np.array([[p.cx, p.cy] for p in particles])

    for i, p in enumerate(particles):
        density = 0.0
        neighbors = tree.query_ball_point([p.cx, p.cy], H)
        for j in neighbors:
            r_vec = positions[i] - positions[j]
            r = np.linalg.norm(r_vec)
            density += particleMass * W_density(r, H)
        p.density = density
        p.pressure = app.stiffness * (density - app.restDensity)



def computeForces(particles, tree, app):
    """Pass 2: compute pressure + viscosity forces for every particle"""
    positions = np.array([[p.cx, p.cy] for p in particles])

    for i, p in enumerate(particles):
        pressureForce = np.zeros(2)
        viscosityForce = np.zeros(2)
        neighbors = tree.query_ball_point([p.cx, p.cy], H)

        for j in neighbors:
            if i == j:
                continue
            neighbor = particles[j]
            r_vec = positions[i] - positions[j]
            r = np.linalg.norm(r_vec)

            # Pressure force: push apart when dense
            if neighbor.density > 0:
                pressureForce += (
                    -particleMass *
                    ((p.pressure + neighbor.pressure) / 2) / neighbor.density *
                    W_pressure_gradient(r_vec, r, H)
                )

            # Viscosity force: drag toward neighbor velocity
            vel_diff = np.array([neighbor.vx - p.vx, neighbor.vy - p.vy])
            if neighbor.density > 0:
                viscosityForce += (
                    app.viscosity * particleMass *
                    vel_diff / neighbor.density *
                    W_viscosity_laplacian(r, H)
                )

        p.fx = pressureForce[0] + viscosityForce[0]
        p.fy = pressureForce[1] + viscosityForce[1]